Fixed some bugs.

diff --git a/urd-bluetooth-connections b/urd-bluetooth-connections
--- a/urd-bluetooth-connections
+++ b/urd-bluetooth-connections
@@ -18,16 +18,31 @@ theme="./common/themes/vertical_menu.rasi"
 TIMEOUT=5
 BTCTL="/usr/bin/bluetoothctl"
 check_runtime_deps "${BTCTL}"
-coproc ${BTCTL}
 
-declare -A act 
-act[connect]='bt_connect'
-act[disconnect]='bt_disconnect'
+btctl(){
+    # To do: fix this function to get return value from btctl 
+    local device="${1?${texts[missingarg]:-Missing argument} device}"
+    shift 1
+    local expect="${1?${texts[missingarg]:-Missing argument} expect}"
+    shift 1
+    local command="$*"
+
+    #coproc btctl { ${BTCTL}; }
+    declare -a lines
+
+    #IFS=$NF read -d '' -a lines <<< $(
+    echo -en "select ${device}\n${command}\nexit" | ${BTCTL}
+
+    #echo "${command}"
+    #[[ "${lines[@]}" =~ "${expect}" ]] && return 0 || return -1
+    return $?
+}
 
 bt_pair(){
-    [ -n "${1}" ] && local client="${1}"
-    [ -n "${2}" ] && local pair="${2}"
-    local btctlpairinfo="$(${BTCTL} -- ${pair} ${client})"
+    # To do: Add possibility to enter passkey if required
+    local client="${1}"
+    local pair="${2}"
+    local btctlpairinfo="$(btctl ${pair} ${client})"
     #local passkey="$( ${GREP} -q "Confirm passkey" <<< "${btctlpairinfo}" && echo "11111" || echo "00000" )"
     #if [ -n ${passkey} ]; then res=$(./urd-confirm -n "${texts[confirmbtpair]:-"Confirm pairing device passkey:"}" "${passkey}")
     #[[ ${res}=="1" ]] && 
@@ -48,19 +63,19 @@ set_device(){
     urgent=""
 
     entries+="$(write_menuentry "${icons[power]} ${texts[power]^}" "${icons[${curr_powered}]}")\n"
-    actions+=("$(echo -e "select ${device}\npower $(toggle "${curr_powered}")" | ${BTCTL} --)")
+    actions+=( "btctl ${device} succseded power $(toggle "${curr_powered}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[power]}")
     
     entries+="$(write_menuentry "${icons[search]} ${texts[btscan]^}" "${icons[${curr_scanning}]}")\n"
-    actions+=("$(echo -e "select ${device}\nscan $(toggle "${curr_scanning}")" | ${BTCTL} --timeout ${TIMEOUT} --)")
+    actions+=( "btctl ${device} Discovery scan $(toggle "${curr_scanning}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[btscan]}")
     
     entries+="$(write_menuentry "${icons[discoverable]} ${texts[discoverable]^}" "${icons[${curr_discoverable}]}")\n"
-    actions+=("$(echo -e "select ${device}\ndiscoverable $(toggle "${curr_discoverable}")" | ${BTCTL} --)")
+    actions+=( "btctl ${device} succeeded discoverable $(toggle "${curr_discoverable}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[discoverable]}")
     
     entries+="$(write_menuentry "${icons[pairable]} ${texts[pairable]^}" "${icons[${curr_pairable}]}")\n"
-    actions+=("$(echo -e "select ${device}\npairable $(toggle "${curr_pairable}")" | ${BTCTL} --)")
+    actions+=( "btctl ${device} succeeded pairable $(toggle "${curr_pairable}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[pairable]}")
 
     header="${texts[deviceoptions]:-"device options"} ${device}"
@@ -71,7 +86,7 @@ set_device(){
 set_client(){
     local index="${1?${texts[missingarg]:-Missing argument} index}"
     local device="${2?${texts[missingarg]:-Missing argument} device}"
-    local client="${bdclients[${1}]%% *}"
+    local client="${clients[${index}]%% *}"
     local name="$( ${SED} -n "s/Alias: \(.\+\)$/\1/p" <<< "${clientinfo[${index}]}" )"
     #local icon="$( ${SED} -n "s/^.\+Icon: \([A-Za-z-]\+\)$/\1/p" <<< "${clientinfo[${index}]}" )"
     local connected="$( ${GREP} -q "Connected: yes" <<< "${clientinfo[${index}]}" && echo "on" || echo "off" )"
@@ -86,31 +101,31 @@ set_client(){
     toggle_trusted=( [off]=trust [on]=untrust )
     toggle_connected=( [off]=connect [on]=disconnect )
 
-    entries="" 
+    entries=""
     actions=()
     error_msgs=()
     active=""
     urgent=""
 
     entries+="$(write_menuentry "${icons[link]} ${texts[${toggle_paired[$paired]}]^}" "${icons[${paired}]}")\n"
-    actions+=("bt_pair ${toggle_paired[${paired}]} ${client}")
-    error_msgs+=("${texts[cantset]:-"can't set"} ${texts[bluetooth]} ${texts[${toggle_paired[${paired}]}]:-"${toggle_paired[${paired}]}"} ${texts[device]} ${name}")
+    actions+=( "bt_pair ${toggle_paired[${paired}]} ${client}" )
+    error_msgs+=("${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_paired[${paired}]}]:-"${toggle_paired[${paired}]}"} ${texts[device]} ${name}")
     
     entries+="$(write_menuentry "${icons[btconnect]} ${texts[${toggle_connected[$connected]}]^}" "${icons[${connected}]}")\n"
-    actions+=("$(echo -e "select ${device}\n${toggle_connected[${connected}]} ${client}" | ${BTCTL} --)")
-    error_msgs+=("${texts[cantset]:-"can't set"} ${texts[bluetooth]} ${texts[${toggle_connected[${connected}]}]:-"${toggle_connected[${connected}]}"} ${texts[device]} ${name}")
+    actions+=( "btctl ${device} Connecting ${toggle_connected[${connected}]} ${client}" )
+    error_msgs+=("${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_connected[${connected}]}]:-"${toggle_connected[${connected}]}"} ${texts[device]} ${name}")
     
     entries+="$(write_menuentry "${icons[trust]} ${texts[${toggle_trusted[$trusted]}]^}" "${icons[${trusted}]}")\n"
-    actions+=("$(echo -e "select ${device}\n${toggle_trusted[$trusted]} ${client}" | ${BTCTL} --)")
-    error_msgs+=("${texts[cantset]:-"can't set"} ${texts[bluetooth]} ${texts[${toggle_trusted[$trusted]}]:-"${toggle_trusted[$trusted]}"} ${texts[device]} ${name}")
+    actions+=( "btctl ${device} Trusting ${toggle_trusted[$trusted]} ${client}" )
+    error_msgs+=( "${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_trusted[$trusted]}]:-"${toggle_trusted[$trusted]}"} ${texts[device]} ${name}" )
     
     entries+="$(write_menuentry "${icons[lock]} ${texts[${toggle_blocked[$blocked]}]^}" "${icons[${blocked}]}")\n"
-    actions+=("$(echo -e "select ${device}\n${toggle_blocked[${blocked}]} ${client}" | ${BTCTL} --)")
-    error_msgs+=("${texts[cantset]:-"can't set"} ${texts[bluetooth]} ${texts[${toggle_blocked[${blocked}]}]:-"${toggle_blocked[${blocked}]}"} ${texts[device]} ${name}")
+    actions+=( "btctl ${device} Block ${toggle_blocked[${blocked}]} ${client}" )
+    error_msgs+=("${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_blocked[${blocked}]}]:-"${toggle_blocked[${blocked}]}"} ${texts[device]} ${name}" )
 
     entries+="$(write_menuentry "${icons[trash]} ${texts[remove]^}" "${icons[yes]}")\n"
-    actions+=("$(echo -e "select ${device}\n${toggle_blocked[${blocked}]} ${client}" | ${BTCTL} --)")
-    error_msgs+=("${texts[cantset]:-"can't set"} ${texts[bluetooth]} ${texts[${toggle_blocked[${blocked}]}]:-"${toggle_blocked[${blocked}]}"} ${texts[device]} ${name}")
+    actions+=( "btctl ${device} Removed remove ${client}" )
+    error_msgs+=( "${texts[cantset]^} ${texts[bluetooth]} ${texts[remove]}]:-"remove"} ${texts[device]} ${name}" )
 
     header="${texts[deviceoptions]:-"device options"} ${name}"
     handle_rofi
@@ -136,14 +151,14 @@ for i in ${!btctl[@]}; do
     bdmacaddr="$(hciconfig -a ${btctl[i]} | ${SED} -n "s/^.\+BD Address: \(${MACADDR_SEDMASK}\) .\+$/\1/p")" 
     bdinfo+=("$(${BTCTL} -- show ${bdmacaddr})")
     bdpowered="$(${GREP} -q "Powered: yes" <<< "${bdinfo[i]}" && echo "on" || echo "off")"
-    bdclients="$(${SED} -n "s/Device \(${MACADDR_SEDMASK} .\+\)$/\1/p" <<< "$(echo -e "select ${bdmacaddr}\ndevices" | ${BTCTL} --)")"
+    bdclients="$(${SED} -n "s/Device \(${MACADDR_SEDMASK} .\+\)$/\1/p" <<< "$(btctl ${bdmacaddr} Device devices)")"
     clients=(); IFS=$NF read -d '' -a clients <<< "${bdclients}"
     entries+="$(write_menuentry "${icons[${bdname%% *}]} ${bdname}" "${icons[${bdpowered}]}")\n"
     actions+=("set_device ${i} ${bdmacaddr}")
-    #warn "Clients: ${!clients[@]} bdclients: ${bdclients}"
+    #warn "Clients: ${clients[@]}"
     #warn "bdinfo: ${bdmacaddr} ${bdpowered}"
     for j in "${!clients[@]}"; do
-        clientinfo+=( "$(echo -e "select ${bdmacaddr}\ninfo ${clients[j]%% *}" | ${BTCTL} --)" )
+        clientinfo+=( "$(btctl ${bdmacaddr} succeeded info "${clients[j]%% *}")" )
         connected="$( ${GREP} -q "Connected: yes" <<< "${clientinfo[j]}" && echo "on" || echo "off" )"
         bticon="bt$( ${SED} -n "s/^.\+Icon: \([A-Za-z-]\+\)$/\1/p" <<< "${clientinfo[$j]}" )"
         btbattery="$( ${SED} -n "s/^.\+Battery Percentage: .\+ (\([0-9]\+\))$/\1/p" <<< "${clientinfo[$j]}" )"
