Temporary fixed scan without device selection

diff --git a/urd-bluetooth-connections b/urd-bluetooth-connections
--- a/urd-bluetooth-connections
+++ b/urd-bluetooth-connections
@@ -21,18 +21,38 @@ BTCTL="/usr/bin/bluetoothctl"
 check_runtime_deps "${BTCTL}"
 
 btctl(){
-    # To do: fix this function to get return value from btctl 
+    # TODO: fix this function to get return value from btctl 
     local device="${1?${texts[missingarg]:-Missing argument} device}"
     shift 1
-    local expect="${1?${texts[missingarg]:-Missing argument} expect}"
+    #local expect="${1?${texts[missingarg]:-Missing argument} expect}"
+    #shift 1
+    local command="$*"
+
+    #coproc btctl { ${BTCTL}; }
+    #declare -a lines
+
+    #IFS=$NF read -d '' -a lines <<< $(
+    echo -en "select ${device}\n${command}\nexit" | ${BTCTL}
+
+    #echo "${command}"
+    #[[ "${lines[@]}" =~ "${expect}" ]] && return 0 || return -1
+    return $?
+}
+
+btscan(){
+    # TODO: fix this function to get return value from btctl 
+    local device="${1?${texts[missingarg]:-Missing argument} device}"
     shift 1
+    #local expect="${1?${texts[missingarg]:-Missing argument} expect}"
+    #shift 1
     local command="$*"
 
     #coproc btctl { ${BTCTL}; }
     declare -a lines
 
-    #IFS=$NF read -d '' -a lines <<< $(
-    echo -en "select ${device}\n${command}\nexit" | ${BTCTL}
+    # TODO: set default device  
+    #${BTCTL} select ${device}
+    ${BTCTL} --timeout ${TIMEOUT} scan ${command}
 
     #echo "${command}"
     #[[ "${lines[@]}" =~ "${expect}" ]] && return 0 || return -1
@@ -64,19 +84,19 @@ set_device(){
     urgent=""
 
     entries+="$(write_menuentry "${icons[power]} ${texts[power]^}" "${icons[${curr_powered}]}")\n"
-    actions+=( "btctl ${device} succseded power $(toggle "${curr_powered}")" )
+    actions+=( "btctl ${device} power $(toggle "${curr_powered}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[power]}")
     
     entries+="$(write_menuentry "${icons[search]} ${texts[btscan]^}" "${icons[${curr_scanning}]}")\n"
-    actions+=( "btctl ${device} Discovery scan $(toggle "${curr_scanning}")" )
+    actions+=( "btscan ${device} $(toggle "${curr_scanning}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[btscan]}")
     
     entries+="$(write_menuentry "${icons[discoverable]} ${texts[discoverable]^}" "${icons[${curr_discoverable}]}")\n"
-    actions+=( "btctl ${device} succeeded discoverable $(toggle "${curr_discoverable}")" )
+    actions+=( "btctl ${device} discoverable $(toggle "${curr_discoverable}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[discoverable]}")
     
     entries+="$(write_menuentry "${icons[pairable]} ${texts[pairable]^}" "${icons[${curr_pairable}]}")\n"
-    actions+=( "btctl ${device} succeeded pairable $(toggle "${curr_pairable}")" )
+    actions+=( "btctl ${device} pairable $(toggle "${curr_pairable}")" )
     error_msgs+=("${texts[cantset]} ${texts[bluetooth]} ${texts[pairable]}")
 
     header="${texts[deviceoptions]:-"device options"} ${device}"
@@ -113,19 +133,19 @@ set_client(){
     error_msgs+=("${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_paired[${paired}]}]:-"${toggle_paired[${paired}]}"} ${texts[device]} ${name}")
     
     entries+="$(write_menuentry "${icons[btconnect]} ${texts[${toggle_connected[$connected]}]^}" "${icons[${connected}]}")\n"
-    actions+=( "btctl ${device} Connecting ${toggle_connected[${connected}]} ${client}" )
+    actions+=( "btctl ${device} ${toggle_connected[${connected}]} ${client}" )
     error_msgs+=("${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_connected[${connected}]}]:-"${toggle_connected[${connected}]}"} ${texts[device]} ${name}")
     
     entries+="$(write_menuentry "${icons[trust]} ${texts[${toggle_trusted[$trusted]}]^}" "${icons[${trusted}]}")\n"
-    actions+=( "btctl ${device} Trusting ${toggle_trusted[$trusted]} ${client}" )
+    actions+=( "btctl ${device} ${toggle_trusted[$trusted]} ${client}" )
     error_msgs+=( "${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_trusted[$trusted]}]:-"${toggle_trusted[$trusted]}"} ${texts[device]} ${name}" )
     
     entries+="$(write_menuentry "${icons[lock]} ${texts[${toggle_blocked[$blocked]}]^}" "${icons[${blocked}]}")\n"
-    actions+=( "btctl ${device} Block ${toggle_blocked[${blocked}]} ${client}" )
+    actions+=( "btctl ${device} ${toggle_blocked[${blocked}]} ${client}" )
     error_msgs+=("${texts[cantset]^} ${texts[bluetooth]} ${texts[${toggle_blocked[${blocked}]}]:-"${toggle_blocked[${blocked}]}"} ${texts[device]} ${name}" )
 
     entries+="$(write_menuentry "${icons[trash]} ${texts[remove]^}" "${icons[yes]}")\n"
-    actions+=( "btctl ${device} Removed remove ${client}" )
+    actions+=( "btctl ${device} remove ${client}" )
     error_msgs+=( "${texts[cantset]^} ${texts[bluetooth]} ${texts[remove]}]:-"remove"} ${texts[device]} ${name}" )
 
     header="${texts[deviceoptions]:-"device options"} ${name}"
@@ -154,14 +174,14 @@ for i in ${!btctl[@]}; do
     bdmacaddr="$(hciconfig -a ${btctl[i]} | ${SED} -n "s/^.\+BD Address: \(${MACADDR_SEDMASK}\) .\+$/\1/p")" 
     bdinfo+=("$(${BTCTL} -- show ${bdmacaddr})")
     bdpowered="$(${GREP} -q "Powered: yes" <<< "${bdinfo[i]}" && echo "on" || echo "off")"
-    bdclients="$(${SED} -n "s/Device \(${MACADDR_SEDMASK} .\+\)$/\1/p" <<< "$(btctl ${bdmacaddr} Device devices)")"
+    bdclients="$(${SED} -n "s/Device \(${MACADDR_SEDMASK} .\+\)$/\1/p" <<< "$(btctl ${bdmacaddr} devices)")"
     clients=(); IFS=$NF read -d '' -a clients <<< "${bdclients}"
     entries+="$(write_menuentry "${icons[${busname}]} ${bdname}" "${icons[${bdpowered}]}")\n"
     actions+=("set_device ${i} ${bdmacaddr}")
     #warn "Clients: ${clients[@]}"
     #warn "bdinfo: ${bdmacaddr} ${bdpowered}"
     for j in "${!clients[@]}"; do
-        clientinfo+=( "$(btctl ${bdmacaddr} succeeded info "${clients[j]%% *}")" )
+        clientinfo+=( "$(btctl ${bdmacaddr} info "${clients[j]%% *}")" )
         connected="$( ${GREP} -q "Connected: yes" <<< "${clientinfo[j]}" && echo "on" || echo "off" )"
         bticon="bt$( ${SED} -n "s/^.\+Icon: \([A-Za-z-]\+\)$/\1/p" <<< "${clientinfo[$j]}" )"
         btbattery="$( ${SED} -n "s/^.\+Battery Percentage: .\+ (\([0-9]\+\))$/\1/p" <<< "${clientinfo[$j]}" )"
