Updated.

diff --git a/common/definitions b/common/definitions
--- a/common/definitions
+++ b/common/definitions
@@ -88,7 +88,7 @@ handle_script_opts() {
                 default_themestr+=" inputbar { enabled: true; } configuration { kb-clear-line: \"\"; }"
             ;;
             -a|--args)
-                while read -d' ' -r arg; do default_rofiargs+=" ${arg}"; done <<< "${2?${texts[missingarg]:-Missing argument}} " || die 1 "Argument required to pass it to rofi."
+                while read -r -d' ' arg; do default_rofiargs+=" ${arg}"; done <<< "${2?${texts[missingarg]:-Missing argument}} " || die 1 "Argument required to pass it to rofi."
                 shift
             ;;
 	        -m|--monitor) 
@@ -127,7 +127,6 @@ handle_rofi() {
     if ${force_dmenu}; then
         [[ -n "${active}" ]] && rofiargs+="-a ${active} -selected-row ${active}"
         [[ -n "${urgent}" ]] && rofiargs+="-u ${urgent}"
-
         chosen_row=$(echo -en "${entries%%\\n}" | ${ROFI} ${rofiargs} -mesg "${header^}" -theme-str "@import \"${theme}\"" -theme-str "${default_themestr}" )
         rofi_ret=$?
         case "${rofi_ret}" in
@@ -211,7 +210,7 @@ toggle() {
 }
 
 check_runtime_deps() {
-    while read -d',' DEP; do
+    while read -r -d',' DEP; do
         command -v ${DEP} >/dev/null 2>&1 || die 1 "${texts[missingruntimedep]:-"Missing runtime dependency"} ${DEP}"
     done <<< "${1?${texts[missingarg]:-Missing argument}}"
 }
@@ -253,9 +252,9 @@ _CTRL_Z_=$'\cZ'
 #     catch_posix STDOUT_VARIABLE STDERR_VARIABLE COMMAND
 catch_posix() {
     {
-        IFS=$NF"${_CTRL_Z_}" read -r -d "${_CTRL_Z_}" "${1}";
-        IFS=$NF"${_CTRL_Z_}" read -r -d "${_CTRL_Z_}" "${2}";
-        ( IFS=$NF"${_CTRL_Z_}" read -r -d "${_CTRL_Z_}" _ERRNO_; return ${_ERRNO_}; )
+        IFS=$NF"${_CTRL_Z_}" read -r -d"${_CTRL_Z_}" "${1}";
+        IFS=$NF"${_CTRL_Z_}" read -r -d"${_CTRL_Z_}" "${2}";
+        ( IFS=$NF"${_CTRL_Z_}" read -r -d"${_CTRL_Z_}" _ERRNO_; return ${_ERRNO_}; )
     } <<EOF
 $( (printf "${_CTRL_Z_}%s${_CTRL_Z_}%d${_CTRL_Z_}" "$( ( ( ({ shift 2; "${@}"; echo "${?}" 1>&3-; } | cut -z -d"${_CTRL_Z_}" -f1 | tr -d '\0' 1>&4-) 4>&2- 2>&1- | cut -z -d"${_CTRL_Z_}" -f1 | tr -d '\0' 1>&4-) 3>&1- | exit "$(cat)") 4>&1-)" "${?}" 1>&2) 2>&1)
 EOF
