Updated.

diff --git a/common/definitions b/common/definitions
--- a/common/definitions
+++ b/common/definitions
@@ -8,7 +8,7 @@ dryrun=false
 force_dmenu=false
 sep='\n'
 default_icons="nf-icons"
-default_rofiargs="-pid /run/user/$(id -u)/rofi.pid -replace -markup-rows -keep-left -sep ${sep} -dmenu"
+default_rofiargs="-pid /run/user/$(id -u)/rofi.pid -replace -cycle -markup-rows -keep-left -sep ${sep} -dmenu"
 default_spanattrs="font_features='dlig=0, -kern, afrc on'"
 default_themestr=""
 default_lang="ru_RU"
@@ -23,12 +23,11 @@ source "./common/icons/$default_icons"
 # Check version of bash for variable indirection
 case $BASH_VERSION in ''|[123].*|4.[012]) die 1 "Bash 4.3+ needed" ; esac
 
-ROFI="rofi"
+ROFI="/usr/bin/rofi"
 SED="sed -u"
 GREP="grep --color=never"
 LS="ls -A --format=single-column --color=never"
 FIND="gfind"
-PRINTF="printf"
 RDEPS+="${ROFI},${SED},${GREP},${LS},${FIND}"
 
 MACADDR_SEDMASK="[[:xdigit:]:]\{11,17\}"
@@ -144,69 +143,70 @@ handle_common_opts() {
 	done
 }
 
+write_script_entries() {
+    get_script_opts "${rofiargs@Q}"
+    [ -n "${prompt}" ] && echo -e "\x00prompt\x1f<span $SPANATTRS>${prompt^}</span>"
+    [ -n "${header}" ] && echo -e "\x00message\x1f<span $SPANATTRS>${header^}</span>"
+    [ -n "${ROFI_DATA}" ] && echo -e "\x00data\x1f${ROFI_DATA}"
+    [ -n "${keepselection}" ] && echo -e "\x00keep-selection\x1f${keepselection}"
+    [ -n "${newselection}" ] && echo -e "\x00new-selection\x1f${newselection}"
+    echo -en "${entries%%\\n}"
+}
+
+get_script_entry_index() {
+    local entry="${1?${texts[missingarg]:-Missing argument} entry}"
+    local line=""
+    local -i i=0
+    local -a lines=()
+
+    return 0
+}
+
 handle_rofi() {
     [[ " ${rofiargs@Q} " =~ " -dmenu " ]] && force_dmenu=true
+    [[ -n "${active}" ]] && rofiargs+=" -a ${active}"
+    [[ -n "${urgent}" ]] && rofiargs+=" -u ${urgent}"
     
     if ${force_dmenu}; then
-        [[ -n "${active}" ]] && rofiargs+=" -a ${active}"
-        [[ -n "${urgent}" ]] && rofiargs+=" -u ${urgent}"
         chosen_row=$(echo -en "${entries%%\\n}" | ${ROFI} ${rofiargs@Q} -mesg "${header^}" -window-title "${header^}" -theme-str "@import \"${theme}\"" -theme-str "${default_themestr}")
         rofi_ret=$?
         case ${rofi_ret} in
-        0) # Entry chosen
-            if [ ${#actions[@]} -gt 0 -a -n "${actions[$chosen_row]}" ]; then
-                if [ ${#confirm[@]} -gt 0 -a "${confirm[$chosen_row]}" == "true" ]; then
-                    ./urd-confirm && \
-                    run_menuentry_action "${actions[$chosen_row]}" "${error_msgs[$chosen_row]}" "${nocatch[$chosen_row]}"
-                else
-                    #send_notification "${actions[$chosen_row]}"
-                    run_menuentry_action "${actions[$chosen_row]}" "${error_msgs[$chosen_row]}" "${nocatch[$chosen_row]}"
-                fi
-            #else
-                #die 1 "${texts[failed]:-"Failed"}: ${texts[varunset]:-"Variable unset"} actions[$chosen_row]"
-            fi
+        0) # rofi: entry chosen
+            run_menuentry_action "${chosen_row}"
         ;;
-        1) # Cancelled by user
+        1) # rofi: cancelled by user
             die 0 "${texts[canceled]:-"Cancelled..."}"
         ;;
-        1[0-9]|2[0-8]) # run new instance on custom key
-	        ./${prog} ${args@Q} ${chosen_row}
+        1[0-9]|2[0-8]) # rofi: pressed custom key
+	        :
         ;;
         *)  die ${rofi_ret} "${texts[error]^}: ${rofi_ret}"
         ;;
         esac
     else
         #warn "direct"
-        get_script_opts "${rofiargs@Q}"
-	    [ -n "${prompt}" ] && echo -e "\x00prompt\x1f<span $SPANATTRS>${prompt^}</span>"
-        [ -n "${header}" ] && echo -e "\x00message\x1f<span $SPANATTRS>${header^}</span>"
-        [ -n "${data}" ] && echo -e "\x00data\x1f${data}"
-        [ -n "${keepselection}" ] && echo -e "\x00keep-selection\x1f${keepselection}"
-        [ -n "${newselection}" ] && echo -e "\x00new-selection\x1f${newselection}"
-
         case ${ROFI_RETV} in
         "") # script called directly
             ${ROFI} ${rofiargs// -dmenu} -modi "urd:./${prog} ${args@Q}" -show urd -theme-str "@import \"${theme}\"" -theme-str "${default_themestr}"
         ;;
         0) # rofi: initial call of script
-  	        echo -en "${entries}"
+            write_script_entries
         ;;
         1) # rofi: selected an entry
-            if [ ${#actions[@]} -gt 0 -a -n "${actions[${@}]}" ]; then
-                if [ ${#confirm[@]} -gt 0 -a -n "${confirm[${@}]}" ]; then
-                    ./urd-confirm && \
-                    run_menuentry_action "${actions[${@}]}" "${error_msgs[${@}]}" "${nocatch[${@}]}"
-                else
-                    run_menuentry_action "${actions[${@}]}" "${error_msgs[${@}]}" "${nocatch[${@}]}"
-                fi
-            #else
-                #die 1 "${texts[failed]:-"Failed"}: ${texts[varunset]:-"Variable unset"} actions[$@]"
-            fi
-
-		    #send_notification "Selected entry... $ROFI_INFO"
+            chosen_row=$(get_script_entry_index "${args}")
+            run_menuentry_action "${chosen_row}"
         ;;
         2) # rofi: selected custom entry
-            warn "Selected custom-entry..."
+            :
+        ;;
+        3) # rofi: deleted entry
+            :
+        ;;
+        1[0-9]|2[0-8]) # rofi: custom key
+	        :
+	    ;;
+        *)  
+            die ${ROFI_RETV} "${texts[error]^}: ${ROFI_RETV}"
         ;;
         esac
     fi
@@ -220,7 +220,8 @@ warn() {
 
 # write error and exit
 die() {
-    local retval=0 # don touch. if statement is urgent here
+    local -i retval=0 
+    # don touch. if statement is urgent here
     if [ -z "${1//[0-9-]/}" ]; then retval=${1}; shift; fi
     if [[ -n "${@}" ]]; then msg="${@}"; else msg="${texts[pogramterminated]^} return = ${retval}"; fi
 	if [ ${retval} -lt 0 ]; then send_notification "${msg^}"; fi
@@ -239,21 +240,21 @@ get_branch_icon(){
     # $2 -- current index (count from 0)
     local arr_len="${1?${texts[missingarg]:-Missing argument} arr_len}"
     local index="${2?${texts[missingarg]:-Missing argument} index}"
-    echo "<span ${SPANATTRS}>${branch[$([ "${arr_len}" -eq "$((${index}+1))" ] && echo 1 || echo 0)]}</span>"
+    echo -n "<span ${SPANATTRS}>${branch[$([ "${arr_len}" -eq "$((${index}+1))" ] && echo 1 || echo 0)]}</span>"
 }
 
 write_menuentry() {
     # Creates listview element menuentry for rofi
     local code="00"
     local text="${1?${texts[missingarg]:-Missing argument} text}"
+    local active="${2}"
     local icon="${3}"
-    local display="${9}"
-    local meta="${6}"
-    local nonselectable="${5}"
     local permanent="${4}"
+    local nonselectable="${5}"
+    local meta="${6}"
     local info="${7}"
     local urgent="${8}"
-    local active="${2}"
+    local display="${9}"
 
     [ -n "${text}" ] && echo -n "<span ${SPANATTRS}>&#x2068;${text}&#x2069;</span>"
     [ -n "${icon}" ] && echo -n "\x${code}icon\x1f${icon}" && code="1f"
@@ -280,29 +281,36 @@ EOF
 }
 
 run_menuentry_action() {
-    local action="${1?${texts[missingarg]:-Missing argument} action}"
-    local error_msg="${2?${texts[missingarg]:-Missing argument} error_msg}"
-    local nocatch="${3:-"false"}"
+    local index="${1?${texts[missingarg]:-Missing argument} index}"
     local catch_output="" 
     local catch_error=""
-    local retcode=1
-    if ${dryrun}; then
-        warn "Dry run: ${action}"
-        warn "error msg: ${error_msg^}"
-        send_notification "Dry run:" "${action} ${error_msg^}"
+    local -i retcode=1
+
+    [ ${#actions[@]} -eq 0 ] && return 0
+    [ -z "${actions[$index]}" ] && return -1
+
+    if [ ${#confirm[@]} -gt 0 -a "${confirm[$index]}" == "true" ]; then
+        ./urd-confirm || return 0
+    fi
+
+    if ${dryrun}; then 
+        warn "Dry run: ${actions[$index]}"
+        warn "error msg: ${error_msgs[$index]^}"
+        send_notification "Dry run:" "${actions[$index]} ${error_msgs[$index]^}"
+        return 0
+    fi
+    
+    if [ ${#nocatch[@]} -gt 0 -a "${nocatch[$index]}" == "true" ]; then
+        ${actions[$index]}
+        retcode=$?
     else
-        if ${nocatch}; then
-            retcode=0
-            ${action}
-        else
-            #send_notification "${action}"
-            catch_posix catch_output catch_error ${action}
-            retcode=$?
-            if [ ${retcode} -ne 0 ] && [ -n "${error_msg}" ]; then 
-                send_notification "${error_msg}" "${catch_error}"
-            fi
-            #warn "Action retcode: ${retcode}, Action: ${action}, Output: ${catch_output}, Error: ${catch_error}, Error msg: ${error_msg}"
+        #send_notification "${action}"
+        catch_posix catch_output catch_error ${actions[$index]}
+        retcode=${catch_error}
+        if [ ${retcode} -ne 0 -a -n "${error_msgs[$index]}" ]; then 
+            send_notification "${error_msgs[$index]}" "${retcode}"
         fi
+        #warn "Action retcode: ${retcode}, Action: ${action}, Output: ${catch_output}, Error: ${catch_error}, Error msg: ${error_msg}"
     fi
     return ${retcode}
 }
@@ -336,7 +344,7 @@ get_device_name(){
     DEV=${DEV##*0000}
     vendor="$(/bin/sed -un 's/^'${VID}'  \(.\+\).*$/\1/p' ${IDS})"
     name="$(/bin/sed -un '/^'${VID}'/,/^\t'${DEV}'/{ s/^\t'${DEV}'  \(.\+\)$/\1/p; }' ${IDS})"
-    echo -ne "${BUS} ${name} ${vendor}"
+    echo -en "${BUS} ${name} ${vendor}"
     return $?
 }
 export -f get_device_name
